import { BrowserWindow, systemPreferences } from "electron";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export let mainWindow: BrowserWindow | null = null;

export const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 750,
        width: 700,
        minHeight: 600,
        minWidth: 400,
        autoHideMenuBar: true,
        resizable: true,
        movable: true,
        titleBarStyle: 'hidden',
        backgroundColor: 'rgb(240, 240, 242)',
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            webSecurity: false,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    mainWindow.webContents.openDevTools();
};